sudo: required
services:
  - docker

before_install:
  - docker pull node:8-onbuild

install:
  - docker build -t probot-hello .

script:
  - docker run --rm probot-hello npm run test
  - docker run --rm probot-hello npm run lint

deploy:
  provider: heroku
  api_key:
    secure: fQjyhnWB7+7MKzYAOtMkTn4d9lM2gFIpxo9+qtuMUwrCaiGY3v2dVW8uny109a4M3F8/tK0uyU2xYFzUc/dhcuT6B4DDHyyXV3Pfh/O8pJfm+cPZImEJUmW2ltl4bPbxQSMbCcdny/enSraGliTs/WzYECdJITYBLy46WDlRkGv/+W46yRedmc9i265tS+jfdsv1QNGKgnAEMOhYxviyr8bmM5gXhTgAba8UnYzkTiW+VlI4lWe/DZsBZFN2+X2bmhoidg16Py14+3v3tvRLW3e05mjOZilgghVj7MvnNoEM8Bb+0rob0b0IiiMHt1aSxGqU7cA5B5qekI3X0wgSUtWOEKnPSmr2NP2NM1jeylHnokKR247EzOrXpZrha0QcowiuJSoF6w+Jw425r1Db4mREzq1hqP74rMA/vNrmX+xzTzNbqMhwxpIM2ZO5Xlyv5xyI5EXNBB9EoyEmWX2dFVu7n9kkGSEIEZzdPIHG78Lu9IVUViSqRPM/tSaWkAj1ZllESPbDBqH9gz9h0trDFl7FiIjir5eEC8KVhuBMGrvFkUG6Sqvtm801XLPjtpdH9vWGbd35WR6oePD9MPLUHQH/IHeki3PUMH1RTBn9HId764vK8vDPtcYB95FfOBF4vLEam6764XjqE/LjZvDUbZFsUfpeCpSrWSz77mMkB78=
  on: heroku_production
  app: leopoppy-probot
