sudo: require
services:
- docker
before_install:
- docker pull node:8-onbuild
install:
- docker build -t probot-hello .
script:
- docker run --rm probot-hello npm run test
- docker run --rm probot-hello npm run lint
deploy:
  provider: heroku
  api_key:
    secure: KSVevB40iIEnvX/3S9MVH2eF446726jbWSLbK7OhMSSl6+ELx0L+hTUJdEE7dnPTpA6BvlM1EopLbe/pF4LoCZ9b54lKbJ0Rg8P9v9UZBLcy1or7Et6bE52ggWiKckx8fjGgjAkmpFYxEAYXrm1cywbEdKnAOGzzu5yDQl4gk3zI8emmxpER8gqeYeT/70BOlHqkkmRmw8tOeF1aoUlDfmRtAGjmIBJgB3g8WcIUbDkIl/9mM5sDxtujiM/Wq9z6pIMS7zaSZ84Yy6PDQpEhcJQAuU91bIFNEdyUUDWzXdVRl6qXk6adRvPST7pIKwi3P3X6DQqZw7j8bHoUsgjJHgNYzfMVqIVvnWRR6ib3q/Wd5ie28S2nCPxbw1QySndInFT2AFaG8306+8Nzwo/hV0I3tL+1UIT3d7sYXSwW5puR7HGuCri9+lO1qoAfKNePjQJdOFA/wi0Hd0TSAI4k54rX6sACk2GcM5JJElUv3kdcyqYrpufBbrd1s6fcYMjDCgLrrgat83cw9pofZd/T1HTdkgJJTjZzKuDM9ZVis7XbSN1LR/y2YbF3iGCI8r/TSnIILFhtDYUOzqYhLlsG1kfh0Sog0S/PckyZVvXkhGhxWW+wTmDxbL32QJptEedUwDQ5jGL26WSxohdpMnF/ahBgu+v42wmITOsZRExhDkU=
  on: heroku_production
  app: probot-fahadharoon